"""
Calendar invitation and email sending tool
"""
from langchain_core.tools import tool
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
import json

def send_interview_invitations(scheduled_interviews: str, job_id: int = None) -> dict:
    """
    Send calendar invitations to candidates and interviewers.
    
    Args:
        scheduled_interviews: JSON string of scheduled interviews
        job_id: Job ID for reference
    
    Returns:
        dict: {
            "calendar_events_created": bool,
            "invites_sent": int,
            "failed_invites": int
        }
    """
    try:
        # Parse input
        if isinstance(scheduled_interviews, str):
            interviews = json.loads(scheduled_interviews)
        else:
            interviews = scheduled_interviews
        
        successful_invites = 0
        failed_invites = 0
        
        for interview in interviews:
            try:
                # Send email to candidate
                candidate_email_sent = send_interview_email_to_candidate(interview)
                
                # Send email to interviewer (optional)
                # interviewer_email_sent = send_interview_email_to_interviewer(interview)
                
                if candidate_email_sent:
                    successful_invites += 1
                else:
                    failed_invites += 1
                    
            except Exception as e:
                print(f"Failed to send invitation for {interview.get('candidate_name')}: {e}")
                failed_invites += 1
        
        return {
            "calendar_events_created": successful_invites > 0,
            "invites_sent": successful_invites,
            "failed_invites": failed_invites,
            "total_processed": len(interviews)
        }
        
    except Exception as e:
        return {
            "calendar_events_created": False,
            "invites_sent": 0,
            "failed_invites": 0,
            "error": str(e)
        }
    

def send_interview_email_to_candidate(interview: dict) -> bool:
    """Send interview invitation email to candidate"""
    try:
        # Email configuration
        smtp_server = "smtp.gmail.com"
        smtp_port = 587
        sender_email = os.getenv("GMAIL_USER")
        sender_password = os.getenv("GMAIL_APP_PASSWORD")
        
        if not sender_email or not sender_password:
            print("Gmail credentials not configured")
            return False
        
        # ✅ DYNAMIC JOB TITLE
        job_title = interview.get('job_title', 'Software Engineer')  # Fallback if not provided
        
        # Create email content with dynamic job title
        subject = f"Interview Invitation - {job_title} Position"
        
        body = f"""
Dear {interview['candidate_name']},

Congratulations! We are pleased to invite you for an interview for the {job_title} position.

Interview Details:
📅 Date: {interview['interview_date']}
🕐 Time: {interview['interview_time']}
🔗 Meeting Link: {interview['meeting_link']}

Interview Format:
• Technical discussion (30 minutes)
• Experience review (20 minutes)  
• Q&A session (10 minutes)

Preparation Tips:
✓ Review the job description and requirements
✓ Prepare examples of your relevant projects
✓ Have questions ready about the role and company
✓ Test your video/audio setup beforehand

Please confirm your availability by replying to this email.

We look forward to meeting you!

Best regards,
DevConnect Recruitment Team

---
This invitation was automatically generated by our AI recruitment system.
"""
        
        # Create and send email
        msg = MIMEMultipart()
        msg['From'] = f"DevConnect Recruitment <{sender_email}>"
        msg['To'] = interview['candidate_email']
        msg['Subject'] = subject
        
        msg.attach(MIMEText(body, 'plain'))
        
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(sender_email, sender_password)
        text = msg.as_string()
        server.sendmail(sender_email, interview['candidate_email'], text)
        server.quit()
        
        print(f"✅ Interview invitation sent to {interview['candidate_name']} for {job_title}")
        return True
        
    except Exception as e:
        print(f"❌ Failed to send email to {interview['candidate_name']}: {e}")
        return False

def send_interview_email_to_interviewer(interview: dict) -> bool:
    """Send interview notification to interviewer"""
    try:
        # Email configuration
        smtp_server = "smtp.gmail.com"
        smtp_port = 587
        sender_email = os.getenv("GMAIL_USER")
        sender_password = os.getenv("GMAIL_APP_PASSWORD")
        
        if not sender_email or not sender_password:
            return False
        
        # ✅ DYNAMIC JOB TITLE
        job_title = interview.get('job_title', 'Software Engineer')
        
        subject = f"Interview Scheduled - {interview['candidate_name']} ({job_title})"
        
        body = f"""
Dear Interviewer,

An interview has been scheduled with one of the shortlisted candidates for the {job_title} position.

Interview Details:
👤 Candidate: {interview['candidate_name']}
💼 Position: {job_title}
📊 Score: {interview.get('candidate_score', 'N/A')}/100
📅 Date: {interview['interview_date']}
🕐 Time: {interview['interview_time']}
🔗 Meeting Link: {interview['meeting_link']}

The candidate has been notified and should confirm their availability soon.

Best regards,
DevConnect AI Recruitment System
"""
        
        # Create and send email
        msg = MIMEMultipart()
        msg['From'] = f"DevConnect Recruitment <{sender_email}>"
        msg['To'] = interview.get('interviewer_email', sender_email)
        msg['Subject'] = subject
        
        msg.attach(MIMEText(body, 'plain'))
        
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(sender_email, sender_password)
        text = msg.as_string()
        server.sendmail(sender_email, interview.get('interviewer_email', sender_email), text)
        server.quit()
        
        print(f"✅ Interview notification sent to interviewer for {job_title}")
        return True
        
    except Exception as e:
        print(f"❌ Failed to send email to interviewer: {e}")
        return False

# def send_interview_email_to_candidate(interview: dict) -> bool:
#     """Send interview invitation email to candidate"""
#     try:
#         # Email configuration
#         smtp_server = "smtp.gmail.com"
#         smtp_port = 587
#         sender_email = os.getenv("GMAIL_USER")
#         sender_password = os.getenv("GMAIL_APP_PASSWORD")
        
#         if not sender_email or not sender_password:
#             print("Gmail credentials not configured")
#             return False
        
#         # Create email content
#         subject = f"Interview Invitation - Backend Engineer Position"
        
#         body = f"""
# Dear {interview['candidate_name']},

# Congratulations! We are pleased to invite you for an interview for the Backend Engineer position.

# Interview Details:
# 📅 Date: {interview['interview_date']}
# 🕐 Time: {interview['interview_time']}
# 🔗 Meeting Link: {interview['meeting_link']}

# Interview Format:
# • Technical discussion (30 minutes)
# • Experience review (20 minutes)  
# • Q&A session (10 minutes)

# Preparation Tips:
# ✓ Review the job description and requirements
# ✓ Prepare examples of your relevant projects
# ✓ Have questions ready about the role and company
# ✓ Test your video/audio setup beforehand

# Please confirm your availability by replying to this email.

# We look forward to meeting you!

# Best regards,
# DevConnect Recruitment Team

# ---
# This invitation was automatically generated by our AI recruitment system.
# """
        
#         # Create and send email
#         msg = MIMEMultipart()
#         msg['From'] = f"DevConnect Recruitment <{sender_email}>"
#         msg['To'] = interview['candidate_email']
#         msg['Subject'] = subject
        
#         msg.attach(MIMEText(body, 'plain'))
        
#         server = smtplib.SMTP(smtp_server, smtp_port)
#         server.starttls()
#         server.login(sender_email, sender_password)
#         text = msg.as_string()
#         server.sendmail(sender_email, interview['candidate_email'], text)
#         server.quit()
        
#         print(f"✅ Interview invitation sent to {interview['candidate_name']}")
#         return True
        
#     except Exception as e:
#         print(f"❌ Failed to send email to {interview['candidate_name']}: {e}")
#         return False

# def send_interview_email_to_interviewer(interview: dict) -> bool:
#     """Send interview notification to interviewer"""
#     try:
#         # Email configuration
#         smtp_server = "smtp.gmail.com"
#         smtp_port = 587
#         sender_email = os.getenv("GMAIL_USER")
#         sender_password = os.getenv("GMAIL_APP_PASSWORD")
        
#         if not sender_email or not sender_password:
#             return False
        
#         subject = f"Interview Scheduled - {interview['candidate_name']}"
        
#         body = f"""
# Dear Interviewer,

# An interview has been scheduled with one of the shortlisted candidates.

# Interview Details:
# 👤 Candidate: {interview['candidate_name']}
# 📊 Score: {interview.get('candidate_score', 'N/A')}/100
# 📅 Date: {interview['interview_date']}
# 🕐 Time: {interview['interview_time']}
# 🔗 Meeting Link: {interview['meeting_link']}

# The candidate has been notified and should confirm their availability soon.

# Best regards,
# DevConnect AI Recruitment System
# """
        
#         # Create and send email
#         msg = MIMEMultipart()
#         msg['From'] = f"DevConnect Recruitment <{sender_email}>"
#         msg['To'] = interview.get('interviewer_email', sender_email)
#         msg['Subject'] = subject
        
#         msg.attach(MIMEText(body, 'plain'))
        
#         server = smtplib.SMTP(smtp_server, smtp_port)
#         server.starttls()
#         server.login(sender_email, sender_password)
#         text = msg.as_string()
#         server.sendmail(sender_email, interview.get('interviewer_email', sender_email), text)
#         server.quit()
        
#         print(f"✅ Interview notification sent to interviewer")
#         return True
        
#     except Exception as e:
#         print(f"❌ Failed to send email to interviewer: {e}")
#         return False